### ISSUE TITLE
Замечания к лабораторной 1

### ISSUE THREAD

**Issue by rredbird66** [Esternit/lab2_pzrl#1]
1. Не собирается. И ошибок многовато. Пока не исправите проверять не могу.
![изображение](https://github.com/Esternit/lab2_pzrl/assets/36138085/84ead745-df7e-4c7d-8bb6-e2ebd5cbe750)
2. В Makefile нет инкрементной сборки. Да и очень слабо выполняется требование по декомпозиции программы. Читайте внимательно задание к лабораторной.

**Comment by Esternit** [comment]
Переделал.

**Comment by rredbird66** [comment]
1. Ошибка сегментации при инверсии.
![изображение](https://github.com/Esternit/lab2_pzrl/assets/36138085/8273a3df-db3c-4f59-9730-5a8360502cdc)
2. Что делает функция check_is_double?
3. В .gitignore не добавлены объектные файлы:
![изображение](https://github.com/Esternit/lab2_pzrl/assets/36138085/7348f01d-eaae-4835-b9d8-4ad05b69c1f1)

**Comment by Esternit** [comment]
1. Исправил(Это единственная ошибка подобная или есть ещё ошибки с тестовым вводом?)
2. Как следует из названия эта функция проверяет, относятся ли входные данные к двоичной СС. Есть такие же функции на проверку на шестнадцатеричную СС и на восьмеричную СС.
3. Исправил gitignore

**Comment by rredbird66** [comment]
2. double - это не двоичная. Двоичная - это binary, double - это число с плавающей точкой двойной точности. Ну терминологию и ключевые термины знать надо всё же. Исправьте. Завтра проверю ```_-_```

Лабораторная работа 2 зачтена.
